action: final newline ci check

diff --git a/.github/workflows/osrd-ui-build.yml b/.github/workflows/osrd-ui-build.yml
--- a/.github/workflows/osrd-ui-build.yml
+++ b/.github/workflows/osrd-ui-build.yml
@@ -45,3 +45,25 @@ jobs:
         }
 
         commit_titles | TERM=xterm-color .github/scripts/check-commit-titles.sh
+
+  final_newline_lint:
+    runs-on: ubuntu-latest
+    name: Check final newline
+    steps:
+      - name: Install ripgrep
+        run: sudo apt-get install -y ripgrep
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Check final newline is present
+        run: |
+          # search missing final newline
+          if rg -Ul '[^\n]\z' -g '!*.svg' .; then
+            echo "Found missing final newline on listed file(s)"
+            exit 1
+          fi
+
+          # search multiple final newlines
+          if rg -Ul '\n\n\z' .; then
+            echo "Found multiple final newlines on listed file(s)"
+            exit 1
+          fi
